### ISSUE TITLE
EveryVoice is broken on GPSC-C due to auto-complete fix

### ISSUE THREAD

**Issue by roedoejet** [EveryVoiceTTS/EveryVoice#591]
### Bug description

I am getting the following when I do anything with the most recent version of EveryVoice on GPSC-C:

running `git checkout dbc2282a34ebf70fb117d1b2ab3e463f820d74bd` fixes it, so there's some issue with the auto-complete. This is only on GPSC-C, everything works fine on my Mac.

### How to reproduce the bug

Try running `everyvoice new-project` on GPSC-C

### Error messages and logs

```(ev3.10) aip000@inter-c-nrc-ubuntu2004 ~/.../experiments/brian_nov_20_24  everyvoice new-project
Traceback (most recent call last):
  File "/space/partner/nrc/work/dt/sgile/opt/miniconda3/envs/ev3.10/bin/everyvoice", line 5, in <module>
    from everyvoice.cli import app
  File "/gpfs/fs3c/nrc/ict/portage/u/tts/code/EveryVoice/everyvoice/cli.py", line 732, in <module>
    CLICK_APP = typer.main.get_group(app)
  File "/home/aip000/.local/lib/python3.10/site-packages/typer/main.py", line 342, in get_group
    group = get_group_from_info(
  File "/home/aip000/.local/lib/python3.10/site-packages/typer/main.py", line 504, in get_group_from_info
    sub_group = get_group_from_info(
  File "/home/aip000/.local/lib/python3.10/site-packages/typer/main.py", line 496, in get_group_from_info
    command = get_command_from_info(
  File "/home/aip000/.local/lib/python3.10/site-packages/typer/main.py", line 590, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
  File "/home/aip000/.local/lib/python3.10/site-packages/typer/main.py", line 566, in get_params_convertors_ctx_param_name_from_function
    click_param, convertor = get_click_param(param)
  File "/home/aip000/.local/lib/python3.10/site-packages/typer/main.py", line 963, in get_click_param
    autocompletion=get_param_completion(parameter_info.autocompletion),
  File "/home/aip000/.local/lib/python3.10/site-packages/typer/main.py", line 1059, in get_param_completion
    raise click.ClickException(
click.exceptions.ClickException: Invalid autocompletion callback parameters: param
```

### Environment

<details>
  <summary>Current environment</summary>

```
absl-py==2.0.0
agate==1.10.2
agate-dbf==0.2.3
agate-excel==0.4.1
agate-sql==0.7.2
aiofiles==23.2.1
aiohttp==3.9.1
aiosignal==1.3.1
altair==5.3.0
aniso8601==9.0.1
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
anytree==2.12.1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
audiomentations==0.37.0
audioread==3.0.1
auraloss==0.4.0
Babel==2.14.0
beautifulsoup4==4.12.3
bidict==0.22.1
black==22.12.0
bleach==6.1.0
blinker==1.7.0
build==1.1.1
cachetools==5.3.1
certifi==2023.11.17
cffi==1.16.0
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.3
clipdetect==0.1.4
cmudict==1.0.30
colorama==0.4.6
coloredlogs==14.0
comm==0.2.2
contourpy==1.2.0
csvkit==2.0.0
cycler==0.12.1
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1702990409666/work
dbfread==2.0.7
debugpy==1.8.5
decorator==5.1.1
-e git+ssh://git@github.com/roedoejet/DeepPhonemizer.git@1b9a1aa4997d5b489a50352d51129ebe2bf41b2e#egg=deep_phonemizer
deepdiff==6.7.1
defusedxml==0.7.1
-e git+ssh://git@github.com/roedoejet/DeepForcedAligner.git@35e10594212445e604f94313c5b21b5a70b0a4bf#egg=dfaligner&subdirectory=../../../../../everyvoice/model/aligner/DeepForcedAligner
distlib==0.3.8
dnspython==2.3.0
editdistance==0.6.2
einops==0.5.0
email-validator==2.1.0.post1
et-xmlfile==1.1.0
eventlet==0.35.0
-e git+ssh://git@github.com/roedoejet/SmallTeamSpeech.git@dbc2282a34ebf70fb117d1b2ab3e463f820d74bd#egg=EveryVoice
exceptiongroup==1.2.0
executing==2.0.1
Fabric3==1.14.post1
fastapi==0.110.3
fastapi-cli==0.0.4
fastjsonschema==2.20.0
ffmpy==0.3.2
filelock==3.13.1
flake8==7.0.0
Flask==2.2.5
Flask-Cors==4.0.0
Flask-RESTful==0.3.10
Flask-SocketIO==5.3.6
flask-talisman==1.1.0
flatbuffers==24.3.25
fonttools==4.47.2
fqdn==1.5.1
Frozen-Flask==1.0.1
frozenlist==1.4.1
fsspec==2023.12.2
g2p @ git+https://git@github.com/roedoejet/g2p.git@251739a5f614714c698662700e0aa3502f68c4d9
gdown==5.1.0
gitlint-core==0.19.1
gradio==4.32.2
gradio_client==0.17.0
grapheme==0.6.0
greenlet==3.0.3
grpcio==1.59.0
gspread==3.6.0
h11==0.14.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
huggingface-hub==0.23.2
humanfriendly==10.0
identify==2.5.33
idna==3.6
importlib_metadata==8.4.0
importlib_resources==6.4.0
iniconfig==2.0.0
ipatok==0.4.1
ipykernel==6.29.5
ipython==8.26.0
ipywidgets==8.1.3
isodate==0.6.1
isoduration==20.11.0
isort==5.13.2
itsdangerous==2.1.2
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
Js2Py==0.74
json5==0.9.25
jsonpath-ng==1.6.1
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.4
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.11
kiwisolver==1.4.5
leather==0.4.0
librosa==0.9.2
lightning==2.1.4
lightning-utilities==0.10.1
lit==17.0.6
llvmlite==0.41.1
loguru==0.6.0
lxml==5.1.0
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.9.2
matplotlib-inline==0.1.7
mccabe==0.7.0
mdurl==0.1.2
merge-args==0.1.5
mistune==3.0.2
mothertongues==0.18.20240126
mpmath==1.3.0
multidict==6.0.4
munkres==1.1.4
mypy==1.8.0
mypy-extensions==1.0.0
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==2.8.4
nltk==3.9.1
nodeenv==1.8.0
notebook==7.2.1
notebook_shim==0.2.4
numba==0.58.1
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1704280375097/work/dist/numpy-1.26.3-cp310-cp310-linux_x86_64.whl#sha256=d6b1cccf494a7701b8dd18911cff7c805fd90e8f4a24cde7c8e40f7805c0765d
numpy-minmax==0.3.1
numpy-rms==0.4.2
oauthlib==3.2.2
olefile==0.47
omegaconf==2.3.0
onnxruntime==1.19.0
openpyxl==3.1.2
ordered-set==4.1.0
orjson==3.10.3
overrides==7.7.0
packaging==23.2
pandas==2.2.1
pandocfilters==1.5.1
panphon==0.20.0
parsedatetime==2.6
parso==0.8.4
pathspec==0.12.1
pep440==0.1.2
pesq==0.0.4
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.1.0
pluggy==1.3.0
pooch==1.8.0
pre-commit==3.6.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==6.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycodestyle==2.11.1
pycountry @ file:///home/conda/feedstock_root/build_artifacts/pycountry_1668531524445/work
pycparser==2.21
pydantic==2.5.3
pydantic_core==2.14.6
pydub==0.25.1
pyflakes==3.2.0
Pygments==2.18.0
pyjsparser==2.7.1
pympi-ling==1.70.2
pyparsing==3.1.1
pyproject_hooks==1.0.0
pysdtw==0.0.5
PySocks==1.7.1
pytest==7.4.4
python-dateutil==2.8.2
python-dotenv==1.0.1
python-engineio==4.8.2
python-json-logger==2.0.7
python-multipart==0.0.9
python-slugify==8.0.2
python-socketio==5.11.0
pytimeparse==1.1.8
pytorch-lightning==2.1.3
pytz==2023.3.post1
pyworld @ file:///home/conda/feedstock_root/build_artifacts/pyworld_1695656915812/work
PyYAML==6.0.1
pyzmq==26.1.0
qtconsole==5.5.2
QtPy==2.4.1
questionary==1.10.0
referencing==0.32.1
regex==2023.12.25
requests==2.32.3
requests-oauthlib==1.3.1
resampy==0.4.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.9.2
rpds-py==0.17.1
rsa==4.9
ruff==0.4.5
safetensors==0.4.5
scikit-learn==1.4.0
scipy==1.11.4
seaborn==0.13.2
semantic-version==2.10.0
Send2Trash==1.8.3
sh==2.0.6
shellingham==1.5.4
silero==0.4.1
silero-vad==5.1
simple-term-menu==1.5.2
simple-websocket==1.0.0
six==1.16.0
sniffio==1.3.1
soundfile==0.12.1
soupsieve==2.5
soxr==0.5.0.post1
SQLAlchemy==2.0.29
stack-data==0.6.3
starlette==0.37.2
sympy==1.12
tabulate==0.9.0
tensorboard==2.16.2
tensorboard-data-server==0.7.1
termcolor==2.3.0
terminado==0.18.1
text-unidecode==1.3
threadpoolctl==3.2.0
tinycss2==1.3.0
tokenizers==0.19.1
tomli==2.0.1
tomlkit==0.12.0
toolz==0.12.1
torch==2.1.0+cu118
torchaudio==2.1.0+cu118
torchinfo==1.8.0
torchmetrics==1.3.0.post0
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
transformers==4.41.2
triton==2.1.0
typer==0.12.5
types-python-dateutil==2.8.19.20240106
types-PyYAML==6.0.12.12
types-requests==2.31.0.20240106
types-setuptools==69.0.0.20240115
types-tabulate==0.9.0.0
typing_extensions==4.12.2
tzdata==2023.4
ujson==5.10.0
unicodecsv==0.14.1
uri-template==1.3.0
urllib3==2.1.0
uvicorn==0.29.0
uvloop==0.19.0
virtualenv==20.25.0
watchfiles==0.22.0
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
websockets==11.0.3
Werkzeug==3.0.0
widgetsnbextension==4.0.11
wsproto==1.2.0
xlrd==2.0.1
yarl==1.9.4
yaspin==3.1.0
zipp==3.20.1
```

</details>

**Comment by joanise** [comment]
I don't have any comparable problems in my own environment. How is this one created and maintained?
The error I get trying to run with that env is that tqdm is missing, so there's something weird with this env, or maybe it's just that I can't use it as non-owner?

**Comment by joanise** [comment]
Can't reproduce. But I just noticed `/home/aip000/.local/lib/python3.10`. Why do you have python packages installed locally? Could it be there's a really old typer in there?
